- package-lock.json
- package.json
- packages/york-core/package.json
- packages/york-react-native/package.json
- packages/york-styleguide/package.json
- packages/york-web/README.md
- packages/york-web/docs/borderRadiuses.md
- packages/york-web/docs/media.md
- packages/york-web/docs/shadows.md
- packages/york-web/docs/sizes.md
- packages/york-web/docs/transitions.md
- packages/york-web/package.json
- packages/york-web/src/components/GridContainer/index.js
- packages/york-web/src/styles.js
Добавил прямой экспорт медиа-брейкпоинтов.
> hotfix-media-constants

- packages/york-react-native/babel.config.js
- packages/york-react-native/src/components/Button/index.js
- packages/york-react-native/src/components/Separator/README.md
- packages/york-react-native/src/components/Separator/index.js
- packages/york-react-native/src/components/Text/README.md
- packages/york-react-native/src/components/Text/index.js
- packages/york-react-native/src/index.js
- packages/york-react-native/src/utils/styles.js
- packages/york-styleguide/propsParser.js
- packages/york-styleguide/webpack.config.js
- packages/york-web/src/components/primitive/Separator/README.md
https://qleanru.atlassian.net/browse/TECH-26
Также затащил сепаратор.
> tech-26-react-native-text

- packages/york-react-native/src/components/Text/index.js
Затупил и случайно сделал `york-rn` зависимым от `york-web`
Это должно пофиксить
> hotfix-rn-text

- lib/components/Navigation/Menu/MenuItem.js
- src/components/Navigation/Menu/MenuItem.js
https://qleanru.atlassian.net/browse/AQN-1865
> aqn-1865-login-btn-fix

- lib/components/Navigation/Menu/index.js
- src/components/Navigation/Menu/index.js
https://qleanru.atlassian.net/browse/AQN-2004
>  aqn-2004-menu-fix 

- packages/york-web/src/components/simple/Tooltip/index.js
не доглядел от предыдущего ПР, нужно больше спанов
> hotfix-tooltip-semantic-again

- packages/york-react-native/src/components/Screen/index.js
Из-за марджинов снизу и сверху был прозрачный фон.
Не нашел лучшего решения, чем обернуть в еще одну вьюху с пэддингами.
> hotfix-screen

- packages/york-react-native/src/components/Checkbox/index.js
- packages/york-react-native/src/components/RadioGroup/index.js
> hotfix-radio-checkbox-2

- packages/york-web/src/components/complex/CallToAction/README.MD
- packages/york-web/src/components/complex/CallToAction/index.js
Переименовал пропы в соответствии с договоренностью:
actionTitle -> buttonTitle
actionHint -> caption
text -> description
> hotfix-call-to-action-naming

- package-lock.json
- packages/york-core/docs/formatters/formatMoney.md
- packages/york-core/src/utils/formatters.js
- packages/york-expo/package-lock.json
- packages/york-styleguide/styleguide.config.js
- packages/york-web/src/components/complex/Header/DesktopHeader/Phone.js
- packages/york-web/src/components/complex/Header/DesktopHeader/Profile/index.js
- packages/york-web/src/components/complex/Header/DesktopHeader/Tabs.js
- packages/york-web/src/components/complex/PromoCard/index.js
Кусочки отсюда https://www.notion.so/ecc9a6a93989413b84e6f19b44f5f6f1
> dom-20-design-fixes

- packages/york-web/src/components/simple/Button/index.js
https://qleanru.atlassian.net/browse/OFF-2179
> off-2179-add-green-button

- packages/york-react-native/src/components/ListItem/index.js
Добавлена поддержка пропов titleProps и captionProps для кастомизации Text внутри ListItem
> hotfix-list-item

- packages/york-web/src/components/simple/Button/index.js
Делаю onClick опциональным чтобы можно было использовать кнопку как ссылку.
> make-on-click-optional

- packages/york-web/src/components/complex/Header/MobileHeader/MobileBurgerHeader/index.js
- packages/york-web/src/components/complex/Header/README.md
`isProfileActive` → `isProfileAvailable`
> hotfix-header-5

- packages/york-react-native/src/components/Screen/index.js
> hotfix-screen-refresh-control-2

- packages/york-react-native/src/components/ListItem/index.js
- packages/york-web/src/components/complex/Header/DesktopHeader/index.js
- packages/york-web/src/components/complex/Header/MobileHeader/index.js
- packages/york-web/src/components/complex/Header/README.md
- packages/york-web/src/components/complex/Header/index.js
- packages/york-web/src/components/complex/Header/utils.js
https://qleanru.atlassian.net/browse/RTN-1974
Добавил в `Header` проп `isNavigationAvailable`, отвечающий за показ/скрытие навигации везде кроме бургерного меню.
> rtn-1974-header-hide-nav

- packages/york-expo/metro.config.js
- packages/york-expo/package-lock.json
- packages/york-react-native/package.json
- packages/york-react-native/src/components/RadioGroup/index.js
- пофиксил обрезание текста в радио селектах
- починил york-expo
- добавил `york-analytics` в пиры для `york-react-native`
> hotfix-rn-radio

- packages/york-react-native/src/components/Text/README.md
- packages/york-react-native/src/components/Text/index.js
- packages/york-web/src/components/primitive/Text/README.md
- packages/york-web/src/components/primitive/Text/index.js
https://qleanru.atlassian.net/browse/RTN-2015
> rtn-2015-text-docs

- packages/york-expo/App.js
- packages/york-react-native/src/components/ListItem/README.md
- packages/york-react-native/src/components/ListItem/index.js
Изменён API `ListItem`: 
- удалены пропы `withArrow `, `titleProps`, `captionProps` и `valueProps`
- `title`, `caption` и `value` теперь принимают в себя не только строковые и численные значения, но и элементы. Стилизация текста теперь реализуется через передачу кастомных Text с нужными пропами
> list-item-update

- packages/york-web/src/components/complex/PromoCard/index.js
https://qleanru.atlassian.net/browse/OFF-2240
> off-2240-responsive-cards

- packages/york-react-native/src/components/ListItem/index.js
- packages/york-react-native/src/components/RadioGroup/index.js
- packages/york-react-native/src/components/RadioItem/README.md
- packages/york-react-native/src/components/RadioItem/index.js
Вынес RadioItem в отдельный компонент. Добавил в ListItem поддержку дополнительных стилей
https://www.figma.com/file/bH0BWYXIbPkU8kbpDbZPr7/%D0%91%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%B0%D1%8F-%D1%81%D0%B4%D0%B5%D0%BB%D0%BA%D0%B0?node-id=95%3A134
> react-native-radio-item

- packages/york-web/src/components/primitive/Modal/index.js
https://qleanru.atlassian.net/browse/DEMAND-4193
> demand-4193-modal

- packages/york-web/src/components/inputs/RadioItem/README.md
- packages/york-web/src/components/inputs/RadioItem/index.js
- packages/york-web/src/components/inputs/index.js
https://qleanru.atlassian.net/browse/DEMAND-4211
> demand-4211-radio-button-web

- packages/york-web/src/components/inputs/RadioItem/index.js
https://qleanru.atlassian.net/browse/DEMAND-4190
> demand-4190-radio-button-fixes
