Qlean/york

packages/york-react-native/src/components/Button/README.md
packages/york-react-native/src/components/Button/index.js
packages/york-web/src/components/simple/Button/index.js

Исправлен баг с выравниванием кнопок по содержимому. Убрал абсолютное позиционирование у заднего слоя с контентом и добавил обоим слоям горизонтальный паддинг.

hotfix-rn-button

---

packages/york-react-native/docs/fontFamily.md
packages/york-react-native/docs/sizes.md
packages/york-react-native/src/components/Button/README.md
packages/york-react-native/src/components/Button/index.js
packages/york-react-native/src/components/index.js
packages/york-react-native/src/index.js
packages/york-styleguide/styleguide.config.js

- добавил экспорт утилзов
- добавил немного документации
- сделал более локальные импорты
- добавил обязательный `onPress` на кнопку, который раньше неявно передавался в `{...props}` для `TouchableOpacity`
- добавил проп `name`, который прокидывается в `testID`
- заменил `children` на `title` в кнопке
Мотивация замены `children` на `title`:
- мы осознанно хотим видеть внутри кнопки только строку
- дефолтный eslint конфиг ругается, если добавлять текст не в компонент `Text`
- дети вида `{foo} {bar}` являются не строкой, а массивом
- нативная кнопка из `react-native` использует проп `title` — https://facebook.github.io/react-native/docs/button#title

tech-1117-rn-button-title

---

packages/york-react-native/src/components/Header/index.js

Фон для хедера теперь белый по умолчанию. Это удобно, потому что у react-navigation фон страницы по умолчанию серый. Ну и с производительностью у прозрачного фона могут быть рандомные проблемы.

hotfix-header-background

---

packages/york-react-native/src/components/Header/index.js

Проп `caption` в хедере был ошибочно помечен как обязательный.

hotfix-header

---

packages/york-react-native/src/components/Header/index.js

Строки не рендерятся вне `Text`.

hotfix-header-2

---

packages/york-web/src/components/simple/Tooltip/index.js

Окно с подсказкой имеет тег `div`, что семантически прибивает его использование только в блочных элементах. Например, если тултип находится в теге `p`, то в консоль свалится куча ошибок.
Учитывая, что он `position: absolute;`, то это изменение никак не затронет визуал, зато, сделает его более семантически правильным, и возможность использовать в инлайновых тегах.
PS не работал ранее с монорепами, если есть какие-то спец правила по работе с ним, то с удовольствием о них узнаю

hotfix-tooltip-semantic

---

packages/york-web/src/components/simple/Tooltip/index.js

Возвращаясь к проблеме line-height в тултипе
Так получается, что при использовании, мне приходится специально оборачивать его, и сбрасывать line-height с тем значением, которое я буду использовать внутри line-height.
Я нахожу такое поведение не правильным, мне кажется, что внутренности тултипа должны зависеть ТОЛЬКО от того, что мы прокидываем внутрь него, а не наследовать что-то извне.
Проблема эта возникает, из-за неправильной композиции элементов, она изложена в следующей статье:
https://stackoverflow.com/questions/11829393/why-is-the-spans-line-height-is-useless
иллюстрация, которая показывает проблему (обратите внимание на div, он занимает значительно большую высоту, нежели сумма трех спанов внутри него):
Возможные решения:
1. избавиться от `StyledTooltipContent`, и рендерить контент …

hotfix-tooltip-lineheight

---

packages/york-web/src/components/simple/Tooltip/index.js

Несколько изменений в тултипе:
— Заменил `useLayoutEffect` на `useEffect`. Кажется, что никаких проблем с этим нет, а первый кидает ворнинги на сервере.
— Поменял паддинги как просил Илья.
— Сделал проверку на элемент. Так-то надо еще переименовать проп для контента на `tooltipNode`, но не в этот раз.

hotfix-tooltip-2

---

packages/york-web/src/components/simple/Tooltip/index.js

Случайно убрал у тултипа `opacity: 0` в прошлом релизе.

tooltip-hotfix-3

---

packages/york-web/src/components/simple/Tooltip/index.js

Очередной фикс тултипа, который позволяет ему нормально оборачивать строчные элементы высота которых меньше чем стандартный line-height.

hotfix-tooltip-3

---

packages/york-web/src/components/primitive/Link/README.md
packages/york-web/src/components/primitive/Link/index.js
packages/york-web/src/components/primitive/index.js
packages/york-web/src/components/simple/index.js

Ссылки должны быть обернуты в текст, а не наоборот. Этот фикс позволяет ссылкам без проблем быть часть какого-то нестандартного текста.

hotfix-link

---

packages/york-web/src/components/simple/GridContainer/index.js

Хочу внести изменения в `GridContainer`, в частности поставить `width: 100%` в мобильном варианте. Это связано с тем, что если контейнер оказывается внутри флекса, то он ужимается по контенту, а это практически никогда не то, что мы хотим получить от сетки, т.к. ее смысл пропадает. На десктопных версиях этого не происходит, потому что там ширина колонок фиксирована.
По идее это ничего не должно сломать, если только вы не использовали `GridContainer` каким-то очень странным образом.

hotfix-grid

---

packages/york-expo/App.js
packages/york-react-native/src/components/Screen/index.js

Пришлось спозиционировать футер абсолютно, чтобы под ним было видно контент. Это нужно для кейсов, как на скриншоте.
Также добавил белый бэкграунд по дефолту.

hotfix-screen-2

---

packages/york-react-native/src/components/Screen/index.js

Обернул `Screen` в `forwardRef`, чтобы прокидывать `ref` в `ScrollView`. https://reactjs.org/docs/forwarding-refs.html
Дифф гитхаба ебнулся немного из-за отступов, на самом деле изменений вот столько:

hotfix-screen-3

---

packages/york-core/src/styles/colors.js

Дизайнеры попросили обновить цвета. Пойдет минорным релизом.
Было / стало
https://www.figma.com/file/8FhFoH32WPPgjto4ksis74/Colors?node-id=23%3A0

new-colors

---

packages/york-react-native/src/components/Screen/index.js

Встроенная в Screen логика отключения скролла ломает работу RefreshControl

hotfix-screen-refresh-control

---

packages/york-web/src/components/simple/Button/index.js

ВНЕЗАПНО выяснил что дефолтное поведение для кнопки это `submit`. Это не ок.

hotfix-button

---

packages/york-web/src/components/complex/Header/MobileHeader/index.js

Меняем приоритет отображения номера в мобильном хедере. Если есть номер — показываем его вместо селектора региона. Выбор региона при этом остается внутри бургера. Требования маркетинга.

hotfix-mobile-header-phone-priority

---

packages/york-core/src/fetcher/index.js

Обычно, фетчер возвращает ответ, пропущенный через `getResponseBody`
Но, запросы, попавшие в очередь из-за рефреша токена, через нее не пропускаются.
В итоге, в сагу влетает не данные полученные с бека, а голый респонс от `fetch`
```
data.constructor.name === 'Response' // true
```

lndr-2299-fix-queue-resp

---

packages/york-web/src/components/complex/ModalWindow/Window.js
packages/york-web/src/components/complex/ModalWindow/index.js
packages/york-web/src/components/primitive/Modal/index.js

В это PR решены две проблемы связанные с модалками:
- Перехват скролла в iOS — см. комменты в коде
- Отступы в Firefox. Он по каким-то причина обрабатывает взаимодействие `padding-bottom` и `overflow: scroll` не так как остальные браузеры (и не признает это багом): https://bugzilla.mozilla.org/show_bug.cgi?id=748518

hotfix-modal

---

packages/york-react-native/src/components/TextInput/index.js

В коллбэки onBlur и onFocus не пробрасывались синтетические ивенты реакта, из-за этого redux-form (и скорее всего другие формы тоже) не могли правильно схендлить эти события

hotfix-react-native-input-events

---

packages/york-react-native/src/components/TextInput/index.js

На андроиде событие попадающее в onBlur не содержит текст, введённый в инпут. Из-за этого редакс-форма отправляет в стор пустое значение при потере фокуса. onEndEditing работает так же как onBlur, кроме того, что значение инпута всё-таки прилетает одинаково на разных платформах
https://stackoverflow.com/questions/34053315/difference-between-onendediting-and-onblur

hotfix-react-native-textinput
